# Verion of docker-compose to use 
version: "3"

services:
  catendar:
    build:
      context: . #Sets the directory for docker-compose to build.

    # Maps port on the local machine to port on Docker image
    ports:
      - "8000:8000"
      
    volumes: 
    # Copy changes made to the project to your image in real-time.
      - .:/catendar
    # Handles the command used to run the project in the Docker container.
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 

    environment:
      # The environment variable credetials that is needed
      # in the settings for Postgres.
      - DB_HOST=db
      - DB_USER=yoyoo
      - DB_PASSWORD=123
      - DB_NAME=catendardb
    
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
    # credentials required by postgres:10-alpine
      - POSTGRES_DB=catendardb
      - POSTGRES_USER=yoyoo
      - POSTGRES_PASSWORD=123