# Generated by Django 3.2.8 on 2021-11-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=50, unique=True)),
                ('decription', models.CharField(default=' ', max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('num_task', models.IntegerField(blank=True, null=True)),
                ('num_taskDone', models.IntegerField(blank=True, default='0', null=True)),
                ('status_prj', models.CharField(choices=[('1', 'Complete'), ('0', 'Incomplete ')], default='0', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status_task', models.CharField(choices=[('1', 'Complete'), ('0', 'Incomplete ')], default='0', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_todo', models.CharField(choices=[('1', 'Complete'), ('0', 'Incomplete ')], default='0', max_length=1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.project')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.task')),
            ],
        ),
    ]
