# Generated by Django 3.2 on 2021-11-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
