# Generated by Django 3.2 on 2021-11-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete ')], default='Incomplete', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete ')], default='Incomplete', max_length=15),
        ),
    ]
