# Generated by Django 3.2 on 2021-12-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avt.png', upload_to='static/images/avt/%Y/%m'),
        ),
    ]
