# Generated by Django 3.2 on 2021-12-07 14:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
